exports.seed = async function(knex) {
  await knex('lines').del()
  await knex('lines').insert([
    {name_en: 'Yamanote Line'},
    {name_en: 'Keihin-Tōhoku Line'},
    {name_en: 'Yokohama Line'},
    {name_en: 'Yokosuka Line'},
    {name_en: 'Keiyo Line'},
    {name_en: 'Saikyo Line'},
    {name_en: 'Shōnan-Shinjuku Line'},
    {name_en: 'Tohoku Main Line'},
    {name_en: 'Tokaido Main Line'},
    {name_en: 'Chūō-Sōbu Line'},
    {name_en: 'Sōbu Main Line'},
    {name_en: 'Chūō Main Line'},
    {name_en: 'Chuo Rapid Line'},
    {name_en: 'Jōban Line'},
    {name_en: 'Ginza Line'},
    {name_en: 'Marunouchi Line'},
    {name_en: 'Hibiya Line'},
    {name_en: 'Tōzai Line'},
    {name_en: 'Chiyoda Line'},
    {name_en: 'Yūrakuchō Line'},
    {name_en: 'Hanzōmon Line'},
    {name_en: 'Namboku Line'},
    {name_en: 'Fukutoshin Line'},
    {name_en: 'Odawara Line'},
    {name_en: 'Enoshima Line'},
    {name_en: 'Tama Line'},
    {name_en: 'Keiō Line'},
    {name_en: 'Keiō Sagamihara Line'},
    {name_en: 'Keiō Takao Line'},
    {name_en: 'Keiō Inokashira Line'},
    {name_en: 'Keiō New Line'},
    {name_en: 'Keiō Dōbutsuen Line'},
    {name_en: 'Keiō Keibajō Line'},
    {name_en: 'Keikyū Main Line'},
    {name_en: 'Asakusa Line'},
    {name_en: 'Mita Line'},
    {name_en: 'Shinjuku Line'},
    {name_en: 'Ōedo Line'},
    {name_en: 'Keisei Main Line'},
    {name_en: 'Oshiage Line'},
    {name_en: 'Chiba Line'},
    {name_en: 'Chihara Line'},
    {name_en: 'Higashi-Narita Line'},
    {name_en: 'Kanamachi Line'},
    {name_en: 'Narita Airport Line'},
    {name_en: 'Tōyoko Line'},
    {name_en: 'Meguro Line'},
    {name_en: 'Den-en-toshi Line'},
    {name_en: 'Ōimachi Line'},
    {name_en: 'Ikegami Line'},
    {name_en: 'Setagaya Line'},
    {name_en: 'Tōkyū Tamagawa Line'},
    {name_en: 'RinkaiLine'},
    {name_en: 'Tōkyō Monorail Haneda Airport Line'},
    {name_en: 'Skytree Line'},
    {name_en: 'Kameido Line'},
    {name_en: 'Daishi Line'},
    {name_en: 'Isesaki Line'},
    {name_en: 'Sano Line'},
    {name_en: 'Koizumi Line'},
    {name_en: 'Kiryū Line'},
    {name_en: 'Nikkō Line'},
    {name_en: 'Utsunomiya Line'},
    {name_en: 'Kinugawa Line'},
    {name_en: 'Urban Park Line'},
    {name_en: 'New Transit Yurikamome'},
  ]);
};