exports.seed = async function(knex) {
  await knex('lines').del()
  await knex('lines').insert([
    {name_en: 'Yamanote Line', operator_id: 1},
    {name_en: 'Keihin-Tōhoku Line', operator_id: 1},
    {name_en: 'Yokohama Line', operator_id: 1},
    {name_en: 'Yokosuka Line', operator_id: 1},
    {name_en: 'Keiyo Line', operator_id: 1},
    {name_en: 'Saikyo Line', operator_id: 1},
    {name_en: 'Shōnan-Shinjuku Line', operator_id: 1},
    {name_en: 'Tohoku Main Line', operator_id: 1},
    {name_en: 'Tokaido Main Line', operator_id: 1},
    {name_en: 'Chūō-Sōbu Line', operator_id: 1},
    {name_en: 'Sōbu Main Line', operator_id: 1},
    {name_en: 'Chūō Main Line', operator_id: 1},
    {name_en: 'Chuo Rapid Line', operator_id: 1},
    {name_en: 'Jōban Line', operator_id: 1},
    {name_en: 'Ginza Line', operator_id: 2},
    {name_en: 'Marunouchi Line', operator_id: 2},
    {name_en: 'Hibiya Line', operator_id: 2},
    {name_en: 'Tōzai Line', operator_id: 2},
    {name_en: 'Chiyoda Line', operator_id: 2},
    {name_en: 'Yūrakuchō Line', operator_id: 2},
    {name_en: 'Hanzōmon Line', operator_id: 2},
    {name_en: 'Namboku Line', operator_id: 2},
    {name_en: 'Fukutoshin Line', operator_id: 2},
    {name_en: 'Odawara Line', operator_id: 3},
    {name_en: 'Enoshima Line', operator_id: 3},
    {name_en: 'Tama Line', operator_id: 3},
    {name_en: 'Keiō Line', operator_id: 4},
    {name_en: 'Keiō Sagamihara Line', operator_id: 4},
    {name_en: 'Keiō Takao Line', operator_id: 4},
    {name_en: 'Keiō Inokashira Line', operator_id: 4},
    {name_en: 'Keiō New Line', operator_id: 4},
    {name_en: 'Keiō Dōbutsuen Line', operator_id: 4},
    {name_en: 'Keiō Keibajō Line', operator_id: 4},
    {name_en: 'Keikyū Main Line', operator_id: 5},
    {name_en: 'Asakusa Line', operator_id: 6},
    {name_en: 'Mita Line', operator_id: 6},
    {name_en: 'Shinjuku Line', operator_id: 6},
    {name_en: 'Ōedo Line', operator_id: 6},
    {name_en: 'Keisei Main Line', operator_id: 7},
    {name_en: 'Oshiage Line', operator_id: 7},
    {name_en: 'Chiba Line', operator_id: 7},
    {name_en: 'Chihara Line', operator_id: 7},
    {name_en: 'Higashi-Narita Line', operator_id: 7},
    {name_en: 'Kanamachi Line', operator_id: 7},
    {name_en: 'Narita Airport Line', operator_id: 7},
    {name_en: 'Tōyoko Line', operator_id: 8},
    {name_en: 'Meguro Line', operator_id: 8},
    {name_en: 'Den-en-toshi Line', operator_id: 8},
    {name_en: 'Ōimachi Line', operator_id: 8},
    {name_en: 'Ikegami Line', operator_id: 8},
    {name_en: 'Setagaya Line', operator_id: 8},
    {name_en: 'Tōkyū Tamagawa Line', operator_id: 8},
    {name_en: 'RinkaiLine', operator_id: 9},
    {name_en: 'Tōkyō Monorail Haneda Airport Line', operator_id: 10},
    {name_en: 'Skytree Line', operator_id: 11},
    {name_en: 'Kameido Line', operator_id: 11},
    {name_en: 'Daishi Line', operator_id: 11},
    {name_en: 'Isesaki Line', operator_id: 11},
    {name_en: 'Sano Line', operator_id: 11},
    {name_en: 'Koizumi Line', operator_id: 11},
    {name_en: 'Kiryū Line', operator_id: 11},
    {name_en: 'Nikkō Line', operator_id: 11},
    {name_en: 'Utsunomiya Line', operator_id: 11},
    {name_en: 'Kinugawa Line', operator_id: 11},
    {name_en: 'Urban Park Line', operator_id: 11},
    {name_en: 'New Transit Yurikamome', operator_id: 12},
  ]);
};