exports.seed = async function(knex) {
  await knex('stations').del();
  await knex('stations').insert([
    {name_en: 'Tokyo Station'},
    {name_en: 'Kanda Station'},
    {name_en: 'Akihabara Station'},
    {name_en: 'Okachimachi Station'},
    {name_en: 'Ueno Station'},
    {name_en: 'Uguisudani Station'},
    {name_en: 'Nippori Station'},
    {name_en: 'Nishi-Nippori Station'},
    {name_en: 'Tabata Station'},
    {name_en: 'Komagome Station'},
    {name_en: 'Sugamo Station'},
    {name_en: 'Otsuka Station'},
    {name_en: 'Ikebukuro Station'},
    {name_en: 'Meijiro Station'},
    {name_en: 'Takadanobaba Station'},
    {name_en: 'Shin-Okubo Station'},
    {name_en: 'Shinjuku Station'},
    {name_en: 'Yoyogi Station'},
    {name_en: 'Harajuku Station'},
    {name_en: 'Shibuya Station'},
    {name_en: 'Ebisu Station'},
    {name_en: 'Meguro Station'},
    {name_en: 'Gotanda Station'},
    {name_en: 'Osaki Station'},
    {name_en: 'Shinagawa Station'},
    {name_en: 'Takanawa Gateway Station'},
    {name_en: 'Tamachi Station'},
    {name_en: 'Hamamatsuchou Station'},
    {name_en: 'Shimbashi Station'},
    {name_en: 'Yurakuchou Station'},
  ]);
};
